stages:
- tests

test:ltr:
  stage: tests
  script:
    - make -C tests FLAVOR=ltr
  tags:
    - factory

test:release:
  stage: tests
  script:
    - make -C tests FLAVOR=release
  tags:
    - factory
